name: Portfolio-webpage
on:
  push:
    branches:
      - main

jobs:
  Check-Docker:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Check Docker Version
        run: docker --version
  login:
    needs: Check-Docker
    runs-on: self-hosted
    steps:
      

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      

  build_and_push:
    runs-on: self-hosted
    needs: login
    steps:
      - uses: actions/checkout@v4
      - name: Push Docker Image to Docker Hub
        run: |
          docker build -t portfolio-webpage:latest . 
          docker tag portfolio-webpage:latest ${{ secrets.DOCKER_USER }}/portfolio-webpage:latest
          docker push ${{ secrets.DOCKER_USER }}/portfolio-webpage:latest

  deploy:
    runs-on: self-hosted
    needs: build_and_push
    steps:
      - uses: actions/checkout@v4
      - name: Deploy Docker Compose
        run: docker compose up -d --force-recreate
  
      
